Upgrade dependencies to target Android Q
gcash/android-neutrino pull request #32
Opened 2019-07-14 22:17 UTC by nighthawk24

Set compile and target SDK version to 29, Migrate android support dependencies to androidx, update corresponding layouts. Stringify resources in layouts. Improve code formatting and remove empty spaces.

2019-07-21 03:22 UTC, zquestz approved these changes

2019-08-01 19:28 UTC, alexshoykhet commented on app/src/main/res/layout/tor_one.xml
> -        android:text="Neutrino Wallet does an excellent job of preventing your peers from learning of your incoming payments. However, outgoing spends are still sent sent in the clear meaning your re
Nit: typo in this string `...are still sent sent in the...` should be `...are still sent in the...`

2019-08-01 19:28 UTC, alexshoykhet commented on app/src/main/res/layout/tor_one.xml
> -        android:text="Neutrino Wallet does an excellent job of preventing your peers from learning of your incoming payments. However, outgoing spends are still sent sent in the clear meaning your re
Nevermind :D I see it's fixed in the strings.xml file

2019-08-01 23:04 UTC, hieronymus777 reviewed
LGTM

2019-08-01 23:33 UTC, zquestz approved these changes
LGTM. Thanks!

2019-08-02 01:33 UTC, cpacia commented
Thanks for putting this together! Only change I'm going to request is fix this regression in both the send and receive activities where the amount is entered. 

Notice the $ (and ₿ symbol when toggled) is not aligned properly and it's showing the error help text with a 0 above.

![Screenshot from 2019-08-01 21-28-29](https://user-images.githubusercontent.com/4504708/62337707-c936ee00-b4a3-11e9-8682-4b731a9f012c.png)

2019-08-02 01:34 UTC, cpacia requested changes
Thanks for putting this together! Only change I'm going to request is fix this regression in both the send and receive activities where the amount is entered.

Notice the $ (and ₿ symbol when toggled) is not aligned properly and it's showing the error help text with a 0 above.

![Screenshot from 2019-08-01 21-28-29](https://user-images.githubusercontent.com/4504708/62337807-1f0b9600-b4a4-11e9-8dec-2407b8f3ddcd.png)

2019-08-06 20:48 UTC, zquestz commented
@nighthawk24 any chance you can look into the regression mentioned by @cpacia ?

2019-08-07 02:09 UTC, nighthawk24 commented
Thank you @cpacia & @zquestz for reviewing and testing the large change. I wanted to get the base setup right before working on feature requests. I've handled the alignment in the layout for now, though the layouts can be refactored to constraint layouts in the future.

2019-08-20 19:09 UTC, zquestz commented
@cpacia this nearly ready? Would be nice to land this.

2019-08-26 02:12 UTC, merged